-- The only active colorscheme. Kanagawa supplies the highlight coverage while
-- this cool-neutral palette replaces its warm yellow and brown defaults.
local c = {
	bg = "#17181c",
	bg_dim = "#141519",
	surface = "#1e1f24",
	float = "#222329",
	selection = "#34303b",
	cursorline = "#24252a",
	border = "#535865",
	fg = "#d7dae0",
	fg_dim = "#aeb2bc",
	muted = "#747b8a",
	rose = "#d4779b",
	lavender = "#b7a0d8",
	mauve = "#a991c3",
	green = "#8fae8b",
	peach = "#d69a7e",
	cyan = "#87a9b8",
	warn = "#c7a86b",
	red = "#d36c6c",
	git_add = "#7f9f7f",
}

return {
	"rebelot/kanagawa.nvim",
	lazy = false,
	priority = 1000,
	config = function()
		require("kanagawa").setup({
			compile = false,
			undercurl = true,
			commentStyle = { italic = true },
			functionStyle = { bold = false },
			keywordStyle = { italic = true },
			statementStyle = { bold = false },
			transparent = true,
			dimInactive = false,
			terminalColors = true,
			theme = "dragon",
			background = {
				dark = "dragon",
				light = "lotus",
			},
			colors = {
				palette = {
					sumiInk0 = c.bg_dim,
					sumiInk1 = c.bg_dim,
					sumiInk2 = c.bg,
					sumiInk3 = c.bg,
					sumiInk4 = c.surface,
					sumiInk5 = "#292a30",
					sumiInk6 = c.border,
					waveBlue1 = "#292a30",
					waveBlue2 = c.selection,
					winterGreen = "#202821",
					winterYellow = "#29282a",
					winterRed = "#2b2225",
					winterBlue = "#25252b",
					autumnGreen = c.git_add,
					autumnRed = c.red,
					autumnYellow = c.mauve,
					samuraiRed = c.red,
					roninYellow = c.warn,
					waveAqua1 = c.cyan,
					waveAqua2 = c.green,
					dragonBlue = c.cyan,
					oldWhite = c.fg_dim,
					fujiWhite = c.fg,
					fujiGray = c.muted,
					oniViolet = c.rose,
					oniViolet2 = c.lavender,
					crystalBlue = c.fg_dim,
					springViolet1 = c.lavender,
					springViolet2 = c.mauve,
					springBlue = c.cyan,
					lightBlue = c.cyan,
					springGreen = c.green,
					boatYellow1 = c.muted,
					boatYellow2 = c.mauve,
					carpYellow = c.lavender,
					sakuraPink = c.peach,
					waveRed = c.rose,
					peachRed = c.red,
					surimiOrange = c.peach,
					katanaGray = c.muted,
					dragonBlack0 = c.bg_dim,
					dragonBlack1 = c.bg_dim,
					dragonBlack2 = c.bg,
					dragonBlack3 = c.bg,
					dragonBlack4 = c.surface,
					dragonBlack5 = "#292a30",
					dragonBlack6 = c.border,
					dragonWhite = c.fg,
					dragonGreen = c.green,
					dragonGreen2 = c.git_add,
					dragonPink = c.rose,
					dragonOrange = c.peach,
					dragonOrange2 = c.peach,
					dragonGray = c.fg_dim,
					dragonGray2 = "#969ca8",
					dragonGray3 = c.muted,
					dragonBlue2 = c.cyan,
					dragonViolet = c.lavender,
					dragonRed = c.red,
					dragonAqua = c.green,
					dragonAsh = c.muted,
					dragonTeal = c.cyan,
					dragonYellow = c.lavender,
				},
				theme = {
					all = {
						ui = {
							fg = c.fg,
							fg_dim = c.fg_dim,
							fg_reverse = c.bg,
							bg_dim = c.bg_dim,
							bg_m3 = c.bg_dim,
							bg_m2 = c.bg_dim,
							bg_m1 = c.bg,
							bg = c.bg,
							bg_p1 = c.surface,
							bg_p2 = "#292a30",
							bg_gutter = "none",
							special = c.rose,
							nontext = c.border,
							whitespace = "#3f424b",
							bg_search = "#55404a",
							bg_visual = c.selection,
							pmenu = {
								fg = c.fg,
								fg_sel = c.fg,
								bg = c.float,
								bg_sel = "#3a3040",
								bg_sbar = "#292a30",
								bg_thumb = c.border,
							},
							float = {
								fg = c.fg,
								bg = c.float,
								fg_border = c.border,
								bg_border = c.float,
							},
						},
						syn = {
							string = c.green,
							variable = "none",
							number = c.peach,
							constant = c.peach,
							identifier = c.fg,
							parameter = c.lavender,
							fun = c.fg_dim,
							statement = c.rose,
							keyword = c.rose,
							operator = "#969ca8",
							preproc = c.mauve,
							type = c.lavender,
							regex = c.green,
							deprecated = c.muted,
							comment = c.muted,
							punct = "#969ca8",
							special1 = c.cyan,
							special2 = c.rose,
							special3 = c.red,
						},
						vcs = {
							added = c.git_add,
							removed = c.red,
							changed = c.mauve,
						},
						diff = {
							add = "#202821",
							delete = "#2b2225",
							change = "#25252b",
							text = c.selection,
						},
						diag = {
							ok = c.green,
							error = c.red,
							warning = c.warn,
							info = c.cyan,
							hint = c.muted,
						},
					},
				},
			},
			overrides = function()
				local float_bg = c.float
				local neotree_bg = "#1b1c21"

				return {
					Normal = { fg = c.fg, bg = "none" },
					NormalNC = { fg = c.fg_dim, bg = "none" },
					EndOfBuffer = { fg = c.bg, bg = "none" },
					SignColumn = { bg = "none" },
					FoldColumn = { fg = c.muted, bg = "none" },
					LineNr = { fg = "#555b68", bg = "none" },
					CursorLineNr = { fg = c.rose, bg = "none", bold = true },
					CursorLine = { bg = c.cursorline },
					ColorColumn = { bg = c.surface },
					Visual = { bg = c.selection },
					Search = { fg = c.fg, bg = "#55404a" },
					IncSearch = { fg = c.bg, bg = c.rose, bold = true },
					Comment = { fg = c.muted, italic = true },
					Function = { fg = c.fg_dim },
					Keyword = { fg = c.rose, italic = true },
					Type = { fg = c.lavender },
					String = { fg = c.green },
					Number = { fg = c.peach },
					Constant = { fg = c.peach },
					DiagnosticError = { fg = c.red },
					DiagnosticWarn = { fg = c.warn },
					DiagnosticInfo = { fg = c.cyan },
					DiagnosticHint = { fg = c.muted },
					DiagnosticVirtualTextError = { fg = c.red, bg = "#2b2225" },
					DiagnosticVirtualTextWarn = { fg = c.warn, bg = "#29282a" },
					DiagnosticVirtualTextInfo = { fg = c.cyan, bg = "#22272a" },
					DiagnosticVirtualTextHint = { fg = c.muted, bg = c.surface },
					NormalFloat = { fg = c.fg, bg = float_bg },
					FloatBorder = { fg = c.border, bg = float_bg },
					FloatTitle = { fg = c.rose, bg = float_bg, bold = true },
					WinSeparator = { fg = "#3f424b", bg = "none" },
					Pmenu = { fg = c.fg, bg = float_bg },
					PmenuSel = { fg = c.fg, bg = "#3a3040", bold = true },
					PmenuSbar = { bg = "#292a30" },
					PmenuThumb = { bg = c.border },
					CmpPmenu = { fg = c.fg, bg = float_bg },
					CmpBorder = { fg = c.border, bg = float_bg },
					CmpItemAbbrMatch = { fg = c.rose, bold = true },
					CmpItemAbbrMatchFuzzy = { fg = c.lavender, bold = true },
					TelescopeNormal = { fg = c.fg, bg = float_bg },
					TelescopeBorder = { fg = c.border, bg = float_bg },
					TelescopePromptNormal = { fg = c.fg, bg = "#292a30" },
					TelescopePromptBorder = { fg = c.rose, bg = "#292a30" },
					TelescopePromptTitle = { fg = c.bg, bg = c.rose, bold = true },
					TelescopeSelection = { fg = c.fg, bg = c.selection, bold = true },
					NeoTreeNormal = { fg = c.fg_dim, bg = neotree_bg },
					NeoTreeNormalNC = { fg = c.fg_dim, bg = neotree_bg },
					NeoTreeEndOfBuffer = { fg = neotree_bg, bg = neotree_bg },
					NeoTreeFloatNormal = { fg = c.fg_dim, bg = float_bg },
					NeoTreeFloatBorder = { fg = c.border, bg = float_bg },
					StatusLine = { fg = c.fg, bg = c.surface },
					StatusLineNC = { fg = c.muted, bg = "#191a1e" },
					BufferLineFill = { fg = c.muted, bg = c.bg_dim },
					GitSignsAdd = { fg = c.git_add, bg = "none" },
					GitSignsChange = { fg = c.mauve, bg = "none" },
					GitSignsDelete = { fg = c.red, bg = "none" },
					NotifyBackground = { bg = float_bg },
					WhichKeyFloat = { bg = float_bg },
					NoiceCmdlinePopup = { bg = float_bg },
					NoiceCmdlinePopupBorder = { fg = c.border, bg = float_bg },
					NoiceCmdlineIcon = { fg = c.rose },
					LazyNormal = { fg = c.fg_dim, bg = float_bg },
					MasonNormal = { fg = c.fg_dim, bg = float_bg },
				}
			end,
		})

		vim.cmd.colorscheme("kanagawa-dragon")
	end,
}
