return {
	"ray-x/go.nvim",
	dependencies = {
		"ray-x/guihua.lua",
		"neovim/nvim-lspconfig",
		"mfussenegger/nvim-dap",
	},
	ft = { "go", "gomod", "gowork", "gosum" },
	cmd = {
		"GoAddTest",
		"GoAddTag",
		"GoAlt",
		"GoBreakToggle",
		"GoBuild",
		"GoCoverage",
		"GoCoverageClear",
		"GoCoverageToggle",
		"GoDebug",
		"GoDoc",
		"GoFillStruct",
		"GoFillSwitch",
		"GoGet",
		"GoGenerate",
		"GoIfErr",
		"GoImpl",
		"GoImport",
		"GoLint",
		"GoModInit",
		"GoModTidy",
		"GoRmTag",
		"GoRun",
		"GoTest",
		"GoTestFile",
		"GoTestFunc",
		"GoTestPkg",
		"GoVet",
	},
	opts = {
		notify = false,
		auto_format = false,
		auto_lint = false,
		gofmt = "gofumpt",
		tag_options = "json=omitempty",
		lsp_cfg = false,
		lsp_keymaps = false,
		lsp_diag_hdlr = false,
		lsp_inlay_hints = {
			enable = true,
			only_current_line = false,
			show_parameter_hints = true,
		},
		test_runner = "go",
		run_in_floaterm = false,
		trouble = false,
		luasnip = true,
		verbose = false,
	},
}
